# Snake Game for 3DS
TARGET := snake3ds
BUILD := build
SOURCE := source
INCLUDES := include
DATA := data
ASSETS := assets
LIBS := -lctru -lm
DEPSDIR := $(BUILD)

ARCH := -march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft
CFLAGS := -Wall -O2 -mword-relocations \
	$(ARCH) $(INCLUDE) -DARM11 -D_3DS
CXXFLAGS := $(CFLAGS) -fno-rtti -fno-exceptions

include $(DEVKITARM)/3ds_rules
